name: thavixt-scrollbar
on: [push]
jobs:
  # vitest, lint, css, coverage
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npx lerna run check --scope @thavixt/scrollbar-*
      - run: npx lerna run test --scope @thavixt/scrollbar-*
      - run: npx lerna run build --scope @thavixt/scrollbar-*

  # deploy demo website to vercel
  deploy:
    needs: test
    runs-on: ubuntu-latest
    # on master branch, if a new tag was pushed
    if: |
      github.ref == 'refs/heads/master' ||
      (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Build Project Artifacts
        run: npm run scrollbar:website:build
        
      - run: cd packages/scrollbar-website
      - name: Link Vercel project
        run: vercel link --cwd dist --yes --project thavixt-scrollbar-demo --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy with Vercel
        run: vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
