name: thavixt-scrollbar
on: [workflow_dispatch, push]
jobs:
  # vitest, lint, css, coverage
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build -w packages/scrollbar-website
      - run: npm run check -w packages/scrollbar-core
      - run: npm run check -w packages/scrollbar-react
      - run: npx lerna run check --scope @thavixt/scrollbar-*
      - run: npx lerna run test --scope @thavixt/scrollbar-*
      - run: npx lerna run build --scope @thavixt/scrollbar-*

  # deploy demo website to vercel
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   # on master branch, if a new tag was pushed
  #   if: |
  #     github.ref == 'refs/heads/master' ||
  #     (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/@thavixt/scrollbar'))
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         # cache: 'npm'
  #         node-version-file: '.nvmrc'
  #     - run: npm ci
  #     - name: Install Vercel CLI
  #       run: npm install --global vercel@latest
      
  #     - name: Build Project Artifacts
  #       run: npm run scrollbar:website:build
        
  #     - name: Link Vercel project
  #       run: vercel link --yes --project thavixt-scrollbar-demo --token=${{ secrets.VERCEL_TOKEN }}
  #     - name: Deploy with Vercel
  #       run: vercel deploy --cwd packages/scrollbar-website/dist --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
