name: thavixt
on:
  workflow_dispatch:
    inputs:
      parameter:
        description: Reason for triggering this workflow
  push:
    branches:
    - 'master' # only on master branch
    tags-ignore:
      - '**' # dont trigger extra runs on tag creation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: (debug) Output workflow trigger event inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      # build all packages
      - run: npx lerna run build
      # upload build folders to use in subsequent jobs
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/*/dist # path to package dist output directories

  vitest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions/download-artifact@v4
      - run: npm ci
      # run vitest
      - run: npm run test

  uikit-cypress:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions/download-artifact@v4
      - run: npm ci
      # run cyct
      - name: Run Cypress component testing for uikit
        run: npm run cyct:run

  uikit-chromatic:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - uses: actions/download-artifact@v4
      - run: npm ci
      # https://www.chromatic.com/docs/cli/#continuous-integration
      - name: Run Chromatic for uikit
        uses: chromaui/action@latest
        with:
          buildScriptName: uikit:storybook:build
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
