name: GitHub Actions Demo
run-name: push - master
on: [push]
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '22.x'
  #     - run: npm ci
  #     - run: npm run lerna:test
  #     - run: npm run coverage

  # chromatic:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '22.x'
  #     - run: npm ci
  #     # https://www.chromatic.com/docs/cli/#continuous-integration
  #     - name: Run Chromatic
  #       uses: chromaui/action@latest
  #       with:
  #         projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  # deploy storybook
  deploy:
    # needs: chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      
      - name: Build Project Artifacts
        run: npm run storybook:build
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Link Vercel project
        run: vercel link --yes --project thavixt-uikit-storybook --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --yes --prod --cwd storybook-static --token=${{ secrets.VERCEL_TOKEN }}

